apiVersion: apps/v1
kind: Deployment 
metadata:
  name: demo-deployment
spec:
  replicas: 2
  strategy: # change here
    type: RollingUpdate # strategy type is Recreate or RollingUpdate. Default is RollingUpdate
  selector:
    matchLabels:
      app: demo-deployment-pod
  template:
    metadata:
      labels:
        app: demo-deployment-pod
    spec:
      containers:
      - image: hoangnguyen147/sample-node-demo
        name: demo-deployment
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: demo-deployment-svc
spec:
  type: NodePort
  selector:
    app: demo-deployment-pod
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
