apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-staging
  labels:
    environment: staging
    project: seminar-k8s
spec:
  containers:
    - image: hoangnguyen147/sample-node-demo
      name: sample-node-container
      ports:
        - containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-uat
  labels:
    environment: uat
    project: seminar-k8s
spec:
  containers:
    - image: hoangnguyen147/sample-node-demo
      name: sample-node-container
      ports:
        - containerPort: 3000
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-prod
  labels:
    environment: prod
    project: seminar-k8s
spec:
  containers:
    - image: hoangnguyen147/sample-node-demo
      name: sample-node-container
      ports:
        - containerPort: 3000
          protocol: TCP
